[general]
import = [
    "~/.config/alacritty/theme/dracula.toml",
]
live_config_reload = true

[env]

[window]
position = "None"
padding = {
    x = 1,
    y = 1
}
dynamic_padding = false
decorations = 'None'
opacity = 1.0

[scrolling]
history = 10000
multiplier = 3

[font]
normal = {
    family = 'JetBrainsMonoNL NF',
    style = 'Regular'
}
size = 16

[selection]
save_to_clipboard = true

[cursor]
style = {
    shape = 'Block',
    blinking = 'Always'
}
vi_mode_style = 'None'
blink_interval = 750

[terminal]
shell = {
    program = '/usr/bin/zsh',
    args = ['-l']
    # tmux
    #args = ['-c', 'tmux new-session']
}

[mouse]
hide_when_typing = true
